# -*- mode: python; -*- 

APPNAME = 'dice.control.rpc'
VERSION = '0.0.1'
top = '.'
build = 'build'

def options(opt):
    opt.load('python')        
    opt.load('compiler_c')

def configure(conf):
    conf.load('python')
    conf.load('compiler_c')
    conf.check_python_headers()
    
def build(bld):
    # bld.add_subdirs(['lib', 'src'])
    bld.add_subdirs(['lib'])

    
