#! /usr/bin/env python

import sys, os, os.path, getopt
import subprocess
import time

import dice.testbench.temperature.lakeshore325 as LK

# --------- Parse command line arguments ------------------

def usage():
    print >>sys.stderr, \
        "usage: bench-lakeshore325-read [--port=port]"

# ---- parse command line -------------

try:
    opts, args = \
        getopt.getopt(sys.argv[1:], "hvrp:", \
                          ["help", "verbose", "port="])
except getopt.GetoptError:
    # print help information and exit
    usage()
    sys.exit(1)
        
# print opts
# print args

port = "/dev/ttyUSB-pl2303-1"
    
for option, arg in opts:
    if option in ("-h", "--help"):
        help()
        sys.exit(0)
    if option in ("-v", "--verbose"):
        verbose = True
    if option in ("-p", "--port"):
        port = arg

# --------- Init LakeShore 325 ----------------------------

L = LK.LakeShore(port = port)

L.open()

# --------- Read ------------------------------------------

temp_A = L.get_temperature("A")
temp_B = L.get_temperature("B")

print time.time(), temp_A, temp_B

# ---------------------------------------------------------

L.close()

# ---------------------------------------------------------



