#!/usr/bin/env python

import sys
import os, os.path, shutil
import glob

captures = glob.glob("*capture.png")
captures.sort()

repetition = 5
if len(sys.argv) > 1:
   repetition = int(sys.argv[1])

tmpdir = 'tmp'

if os.path.isdir(tmpdir):
   shutil.rmtree(tmpdir)
os.mkdir(tmpdir)

i = 0
for cap in captures:
   for rep in xrange(repetition):
      symlinkname = os.path.join('tmp', '%03d.png' % i)
      os.link(cap, symlinkname)
      i += 1

# create the video

os.system("avconv -f image2 -i %s/%%03d.png -s 1278x736 -q 1 -r 24 output.avi" % tmpdir)

